[project]
name = "news-aggregator-telegram"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Vyacheslav", email = "nodegopher@gmail.com" }
]
dependencies = [
    "aiogram>=3.9.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []
